# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e21b0db2b81feafdb76f0b844d7b1f1592d4b6f2b5bdfadadc20b1eaffe03a0a47c9e80cd87879a38e602fee372c5184ea5b8cd85f46f9cab50b564c5521ca5

test:
  secret_key_base: d33487fb6d213859db12637922936c7129ba0bd97a6746fba52cfdb77bfef0ad73dadd43e6aa21641bc59811468a8215f604cd69c9cb1e3cabdb49a82d2fc77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
